import { PoseLandmarker, FilesetResolver } from "https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.35/vision_bundle.mjs";

const APP = "CPR Research System Mode 3 V1.3-diagnostic";
const TASKS = "@mediapipe/tasks-vision@0.10.35", WASM = `https://cdn.jsdelivr.net/npm/${TASKS}/wasm`;
const MP_URL = "https://storage.googleapis.com/mediapipe-models/pose_landmarker/pose_landmarker_full/float16/1/pose_landmarker_full.task", MOVENET_URL = "https://tfhub.dev/google/tfjs-model/movenet/singlepose/thunder/4";
const MODELS = { mediapipe_full: { label: "MediaPipe Pose Landmarker Full", family: "MediaPipe Pose Landmarker", variant: "Full", count: 33, confidence: "MediaPipe landmark visibility estimate", url: MP_URL }, movenet_thunder: { label: "MoveNet SinglePose Thunder", family: "MoveNet", variant: "SinglePose Thunder", count: 17, confidence: "MoveNet keypoint score", url: MOVENET_URL } };
const MP = { nose: 0, left_shoulder: 11, right_shoulder: 12, left_elbow: 13, right_elbow: 14, left_wrist: 15, right_wrist: 16, left_hip: 23, right_hip: 24 }, MN = { nose: 0, left_shoulder: 5, right_shoulder: 6, left_elbow: 7, right_elbow: 8, left_wrist: 9, right_wrist: 10, left_hip: 11, right_hip: 12 };
const POINTS = ["nose", "neck_mid", "left_shoulder", "right_shoulder", "left_elbow", "right_elbow", "left_wrist", "right_wrist", "left_hip", "right_hip"], SIDES = ["left", "right"];
// These values are diagnostic safeguards only, not calibrated research thresholds.
const CONTINUITY_SEC = .5, JUMP_NORMALIZED = .12;
const $ = id => document.getElementById(id), e = Object.fromEntries(["videoFile", "modelSelect", "startBtn", "stopBtn", "replayBtn", "video", "canvas", "videoCard", "message", "badge", "fileName", "resolution", "progress", "rowCount", "poseFps", "detectionMs", "rateBpm", "downloadCsvBtn", "downloadMetadataBtn"].map(id => [id, $(id)]));
let file, url, mp, moveNet, running = false, replaying = false, rows = [], times = [], detections = [], signal = [], lastRate = "", lastTime = -1, duration = 0, raf = 0, activeModelKey = "", runInfo = {}, sideState = {};
const round = (v, d = 3) => Number.isFinite(v) ? Number(v.toFixed(d)) : "", mean = a => a.length ? a.reduce((s, v) => s + v, 0) / a.length : 0, model = (key = e.modelSelect.value) => MODELS[key];
const set = (id, value) => e[id].textContent = value, notice = value => e.message.textContent = value;
function progress(time) { set("progress", Number.isFinite(duration) && duration > 0 && Number.isFinite(time) ? `${Math.min(100, Math.max(0, 100 * time / duration)).toFixed(1)}%` : "—"); }
function escapeCsv(value) { const text = String(value ?? ""); return /[\",\n]/.test(text) ? `"${text.replaceAll('"', '""')}"` : text; }
function distance(a, b) { return a && b && Number.isFinite(a.x) && Number.isFinite(a.y) && Number.isFinite(b.x) && Number.isFinite(b.y) ? Math.hypot(a.x - b.x, a.y - b.y) : NaN; }
function neck(points) { const left = points.left_shoulder, right = points.right_shoulder; if (left && right) points.neck_mid = { x: (left.x + right.x) / 2, y: (left.y + right.y) / 2, z: Number.isFinite(left.z) && Number.isFinite(right.z) ? (left.z + right.z) / 2 : "", visibility: Number.isFinite(left.visibility) && Number.isFinite(right.visibility) ? (left.visibility + right.visibility) / 2 : "" }; return points; }
function mpPoints(items) { const points = {}; for (const [name, index] of Object.entries(MP)) { const item = items?.[index]; if (item) points[name] = { x: item.x, y: item.y, z: item.z, visibility: item.visibility ?? "" }; } return neck(points); }
function moveNetPoints(items) { const points = {}; for (const [name, index] of Object.entries(MN)) { const item = items?.[index]; if (item && Number.isFinite(item.x) && Number.isFinite(item.y)) points[name] = { x: item.x / e.video.videoWidth, y: item.y / e.video.videoHeight, z: "", visibility: item.score ?? "" }; } return neck(points); }
function draw(points) { const rect = e.canvas.getBoundingClientRect(), ratio = devicePixelRatio || 1, ctx = e.canvas.getContext("2d"); e.canvas.width = rect.width * ratio; e.canvas.height = rect.height * ratio; ctx.setTransform(ratio, 0, 0, ratio, 0, 0); ctx.clearRect(0, 0, rect.width, rect.height); const line = (a, b, color) => { if (!points[a] || !points[b]) return; ctx.strokeStyle = color; ctx.lineWidth = 4; ctx.beginPath(); ctx.moveTo(points[a].x * rect.width, points[a].y * rect.height); ctx.lineTo(points[b].x * rect.width, points[b].y * rect.height); ctx.stroke(); }; [["left_shoulder", "left_elbow", "#22d3ee"], ["left_elbow", "left_wrist", "#22d3ee"], ["right_shoulder", "right_elbow", "#facc15"], ["right_elbow", "right_wrist", "#facc15"], ["left_shoulder", "left_hip", "#34d399"], ["right_shoulder", "right_hip", "#34d399"]].forEach(v => line(...v)); Object.values(points).forEach(item => { ctx.fillStyle = "#fff"; ctx.beginPath(); ctx.arc(item.x * rect.width, item.y * rect.height, 4, 0, Math.PI * 2); ctx.fill(); }); }
function rolling(array, item, seconds) { if (!Number.isFinite(item.v)) return; array.push(item); while (array.length && array[0].t < item.t - seconds) array.shift(); }
function range(array) { const values = array.filter(Number.isFinite).sort((a, b) => a - b); return values.length < 5 ? "" : values[Math.floor(.9 * (values.length - 1))] - values[Math.floor(.1 * (values.length - 1))]; }
function smooth(array) { return array.map((_, index) => mean(array.slice(Math.max(0, index - 2), Math.min(array.length, index + 3)))); }
function rate() { const points = signal.filter(item => Number.isFinite(item.v)); if (points.length < 90) return ""; const values = points.map(item => item.v), amplitude = range(values); if (!Number.isFinite(amplitude) || amplitude < 5) return ""; const smoothed = smooth(values), threshold = Math.min(12, Math.max(3, amplitude * .18)), peaks = []; let last = -Infinity; for (let index = 2; index < smoothed.length - 2; index++) { const value = smoothed[index], time = points[index].t; if (value > smoothed[index - 1] && value >= smoothed[index + 1] && value > smoothed[index - 2] && value >= smoothed[index + 2] && value - Math.min(...smoothed.slice(Math.max(0, index - 8), Math.min(smoothed.length, index + 9))) >= threshold && time - last >= .32) { peaks.push(time); last = time; } } if (peaks.length < 4) return ""; const bpm = (peaks.length - 1) / (peaks.at(-1) - peaks[0]) * 60; return bpm >= 40 && bpm <= 180 ? bpm : ""; }
function compression(points) { const shoulder = points.left_shoulder, wrist = points.left_wrist, height = e.video.videoHeight; if (Number.isFinite(shoulder?.y) && Number.isFinite(wrist?.y)) return (.65 * wrist.y + .35 * shoulder.y) * height; if (Number.isFinite(wrist?.y)) return wrist.y * height; if (Number.isFinite(shoulder?.y)) return shoulder.y * height; return ""; }
function resetSideState() { sideState = Object.fromEntries(SIDES.map(side => [side, { previous: null, validFrom: null, reasonCounts: {} }])); }
function assessSide(side, points, time) { const chain = [`${side}_shoulder`, `${side}_elbow`, `${side}_wrist`].map(key => points[key]), state = sideState[side], missing = chain.some(v => !v || !Number.isFinite(v.x) || !Number.isFinite(v.y)), outOfFrame = !missing && chain.some(v => v.x < 0 || v.x > 1 || v.y < 0 || v.y > 1), jump = state.previous && !missing ? Math.max(...chain.map((v, i) => distance(v, state.previous[i]))) : 0, jumpDetected = Number.isFinite(jump) && jump > JUMP_NORMALIZED; let reason = missing ? "MISSING_LANDMARK" : outOfFrame ? "OUT_OF_FRAME" : jumpDetected ? "LANDMARK_JUMP" : "ASSESSABLE"; if (reason === "ASSESSABLE") { if (!Number.isFinite(state.validFrom)) state.validFrom = time; } else state.validFrom = null; const continuity = Number.isFinite(state.validFrom) ? Math.max(0, time - state.validFrom) : 0; if (reason === "ASSESSABLE" && continuity < CONTINUITY_SEC) reason = "INSUFFICIENT_CONTINUITY"; state.previous = missing ? null : chain.map(v => ({ x: v.x, y: v.y })); state.reasonCounts[reason] = (state.reasonCounts[reason] || 0) + 1; const confidence = chain.map(v => v?.visibility).filter(Number.isFinite); return { assessable: reason === "ASSESSABLE", reason, confidence: confidence.length ? Math.min(...confidence) : "", shoulderElbow: distance(chain[0], chain[1]), elbowWrist: distance(chain[1], chain[2]), jump: jump || 0, continuity }; }
function row(points, time, detectionMs, compressionSignal, bpm) { const current = model(activeModelKey), out = { app_version: APP, analysis_type: "local_reanalysis_model_comparison", frame_index: rows.length, elapsed_sec: round(time, 4), video_time_sec: round(time, 4), pose_count: Object.keys(points).length ? 1 : 0, detection_ms: round(detectionMs), frame_interval_ms: lastTime < 0 ? "" : round((time - lastTime) * 1000), compression_signal_px: round(compressionSignal, 2), rate_bpm_estimate: round(bpm, 2), model_key: activeModelKey, model_label: current.label, model_confidence_semantics: current.confidence }; for (const name of POINTS) for (const key of ["x", "y", "z", "visibility"]) out[`${name}_${key}`] = points[name]?.[key] ?? ""; for (const side of SIDES) { const value = assessSide(side, points, time); out[`${side}_side_assessable_preliminary`] = value.assessable; out[`${side}_reason_code`] = value.reason; out[`${side}_confidence_summary_native`] = round(value.confidence, 4); out[`${side}_shoulder_elbow_length_normalized`] = round(value.shoulderElbow, 5); out[`${side}_elbow_wrist_length_normalized`] = round(value.elbowWrist, 5); out[`${side}_landmark_jump_normalized`] = round(value.jump, 5); out[`${side}_continuous_valid_duration_sec`] = round(value.continuity, 4); } return out; }
async function dispose() { mp?.close(); mp = undefined; moveNet?.dispose(); moveNet = undefined; }
async function prepare() { await dispose(); if (activeModelKey === "mediapipe_full") { const vision = await FilesetResolver.forVisionTasks(WASM); mp = await PoseLandmarker.createFromOptions(vision, { baseOptions: { modelAssetPath: MP_URL, delegate: "GPU" }, runningMode: "VIDEO", numPoses: 1, minPoseDetectionConfidence: .5, minTrackingConfidence: .5 }); return; } if (!window.tf || !window.poseDetection) throw new Error("MoveNet 依賴尚未載入；請確認網路或本機資源。"); await window.tf.setBackend("webgl"); await window.tf.ready(); moveNet = await window.poseDetection.createDetector(window.poseDetection.SupportedModels.MoveNet, { modelType: window.poseDetection.movenet.modelType.SINGLEPOSE_THUNDER, enableSmoothing: false }); }
async function detect() { return mp ? mpPoints(mp.detectForVideo(e.video, performance.now()).landmarks?.[0]) : moveNetPoints((await moveNet.estimatePoses(e.video, { flipHorizontal: false }))[0]?.keypoints); }
function waitForEvent(event, timeoutMs = 10000) { return new Promise((resolve, reject) => { const timeout = setTimeout(() => { cleanup(); reject(new Error(`${event} 等待逾時`)); }, timeoutMs), done = () => { cleanup(); resolve(); }, cleanup = () => { clearTimeout(timeout); e.video.removeEventListener(event, done); }; e.video.addEventListener(event, done, { once: true }); }); }
async function seekToStart() { if (Math.abs(e.video.currentTime) < .001) return; const done = waitForEvent("seeked"); e.video.currentTime = 0; await done; }
async function warmUp() { notice(`${model(activeModelKey).label} 已載入，正在 warm-up；影片尚未開始正式分析。`); await seekToStart(); const started = performance.now(); await detect(); runInfo.warmup_detection_ms = round(performance.now() - started, 2); await seekToStart(); }
async function tick() { if (!running) return; const time = e.video.currentTime; if (time !== lastTime && e.video.readyState >= 2) { const started = performance.now(); let points; try { points = await detect(); } catch (error) { finish(`推論失敗：${error.message}`); return; } const detectionMs = performance.now() - started, compressionSignal = compression(points); rolling(signal, { t: time, v: compressionSignal }, 12); const bpm = rate(); if (Number.isFinite(bpm)) lastRate = bpm; rows.push(row(points, time, detectionMs, compressionSignal, bpm)); times.push(time); detections.push(detectionMs); lastTime = time; if (!Number.isFinite(runInfo.first_valid_inference_elapsed_sec)) runInfo.first_valid_inference_elapsed_sec = round(time, 4); draw(points); progress(time); set("rowCount", rows.length); set("poseFps", times.length > 1 ? `${(rows.length / (time - times[0])).toFixed(2)} fps` : "—"); set("detectionMs", `${mean(detections).toFixed(1)} ms`); set("rateBpm", Number.isFinite(bpm) ? `${Math.round(bpm)} 次/分鐘` : "估算中"); e.badge.textContent = `分析中｜${model(activeModelKey).label}｜${time.toFixed(2)} s｜${rows.length} 筆`; } raf = requestAnimationFrame(tick); }
function base() { return `${file.name.replace(/\.(webm|mp4)$/i, "").replace(/_raw$/i, "")}_reanalyzed_${activeModelKey}`; }
function download(text, name, type) { const anchor = document.createElement("a"), objectUrl = URL.createObjectURL(new Blob([text], { type })); anchor.href = objectUrl; anchor.download = name; anchor.click(); setTimeout(() => URL.revokeObjectURL(objectUrl), 1000); }
function durationInfo() { const native = Number.isFinite(duration) && duration > 0 ? duration : null, fallback = times.length ? times.at(-1) : null; return { duration_sec: native ?? fallback, duration_source: native ? "video_loadedmetadata" : fallback !== null ? "max_analyzed_elapsed_sec_fallback" : "unavailable" }; }
function summary(side) { const counts = sideState[side].reasonCounts, total = Object.values(counts).reduce((sum, count) => sum + count, 0); return { reason_counts: counts, assessable_ratio: total ? round((counts.ASSESSABLE || 0) / total, 4) : null }; }
function metadata() { const current = model(activeModelKey), maxGap = times.length > 1 ? Math.max(...times.slice(1).map((time, i) => (time - times[i]) * 1000)) : null; return { status: "finished", analysis_type: "local_reanalysis_model_comparison", source_video: { filename: file.name, size_bytes: file.size, width: e.video.videoWidth, height: e.video.videoHeight, ...durationInfo() }, model: { key: activeModelKey, family: current.family, variant: current.variant, landmark_count: current.count, resource_url: current.url, confidence_field: activeModelKey === "mediapipe_full" ? "visibility" : "score", confidence_semantics: current.confidence, cross_model_confidence_comparable: false, smoothing_enabled: false }, analysis: { row_count: rows.length, pose_row_count: rows.filter(v => v.pose_count).length, pose_fps_mean: times.length > 1 ? rows.length / (times.at(-1) - times[0]) : null, detection_ms_mean: mean(detections), rate_bpm_estimate_final: round(lastRate, 2), model_ready_elapsed_sec: runInfo.model_ready_elapsed_sec, warmup_detection_ms: runInfo.warmup_detection_ms, first_valid_inference_elapsed_sec: runInfo.first_valid_inference_elapsed_sec ?? null, maximum_frame_gap_ms: round(maxGap, 2), assessability_diagnostic: { preliminary_only: true, confidence_threshold_applied: false, continuity_requirement_sec: CONTINUITY_SEC, jump_threshold_normalized: JUMP_NORMALIZED, left: summary("left"), right: summary("right"), note: "Uncalibrated Mode 3 data-quality diagnostics only. They do not classify posture, alter raw landmarks, or establish formal research thresholds." }, generated_at: new Date().toISOString(), note: "Original video and prior CSV files were not changed. MoveNet score and MediaPipe visibility are not interchangeable thresholds; rate is not QCPR." } }; }
function nearestRow(time) { if (!rows.length) return null; let low = 0, high = rows.length - 1; while (low < high) { const middle = Math.floor((low + high) / 2); if (Number(rows[middle].elapsed_sec) < time) low = middle + 1; else high = middle; } const current = rows[low], previous = rows[Math.max(0, low - 1)]; return Math.abs(Number(previous.elapsed_sec) - time) <= Math.abs(Number(current.elapsed_sec) - time) ? previous : current; }
function replayFrame() { if (!replaying || running) return; const item = nearestRow(e.video.currentTime); if (!item) return; const points = {}; for (const name of POINTS) { const x = Number(item[`${name}_x`]), y = Number(item[`${name}_y`]); if (Number.isFinite(x) && Number.isFinite(y)) points[name] = { x, y }; } draw(points); e.badge.textContent = `回放｜${model(activeModelKey).label}｜左：${item.left_reason_code || "—"}｜右：${item.right_reason_code || "—"}`; progress(e.video.currentTime); }
function finish(reason = "分析完成") { if (!running) return; running = false; cancelAnimationFrame(raf); e.video.pause(); progress(lastTime); e.startBtn.disabled = false; e.modelSelect.disabled = false; e.stopBtn.disabled = true; e.replayBtn.disabled = !rows.length; e.downloadCsvBtn.disabled = !rows.length; e.downloadMetadataBtn.disabled = !rows.length; e.badge.textContent = `${reason}｜${model(activeModelKey).label}｜${rows.length} 筆`; notice(`${reason}。可下載新的 CSV 與 metadata，或回放本次骨架；原始影片未被改動。`); }
e.videoFile.addEventListener("change", () => { file = e.videoFile.files[0]; if (!file) return; if (url) URL.revokeObjectURL(url); duration = 0; replaying = false; rows = []; e.replayBtn.disabled = true; e.replayBtn.textContent = "回放本次骨架"; progress(NaN); url = URL.createObjectURL(file); e.video.src = url; set("fileName", file.name); notice("影片已選擇；載入資訊後可開始。"); e.startBtn.disabled = true; });
e.video.addEventListener("loadedmetadata", () => { duration = e.video.duration; progress(0); set("resolution", `${e.video.videoWidth} × ${e.video.videoHeight}`); e.videoCard.style.setProperty("--video-aspect", `${e.video.videoWidth} / ${e.video.videoHeight}`); e.startBtn.disabled = false; });
e.video.addEventListener("timeupdate", () => { progress(e.video.currentTime); replayFrame(); }); e.video.addEventListener("seeked", replayFrame); e.video.addEventListener("ended", () => { if (running) finish(); else replayFrame(); });
e.startBtn.addEventListener("click", async () => { try { replaying = false; activeModelKey = e.modelSelect.value; e.startBtn.disabled = true; e.modelSelect.disabled = true; e.replayBtn.disabled = true; e.downloadCsvBtn.disabled = true; e.downloadMetadataBtn.disabled = true; rows = []; times = []; detections = []; signal = []; lastRate = ""; lastTime = -1; resetSideState(); runInfo = { first_valid_inference_elapsed_sec: null }; set("rateBpm", "估算中"); notice(`正在載入 ${model(activeModelKey).label}；影片不會開始播放。`); const started = performance.now(); await prepare(); runInfo.model_ready_elapsed_sec = round((performance.now() - started) / 1000, 4); await warmUp(); await seekToStart(); notice("模型 warm-up 完成，現在從 0 秒開始正式分析。"); running = true; e.stopBtn.disabled = false; await e.video.play(); tick(); } catch (error) { running = false; e.startBtn.disabled = false; e.modelSelect.disabled = false; e.stopBtn.disabled = true; notice(`無法開始：${error.message}`); } });
e.stopBtn.addEventListener("click", () => finish("使用者停止"));
e.replayBtn.addEventListener("click", () => { if (!rows.length) return; replaying = !replaying; e.replayBtn.textContent = replaying ? "結束骨架回放" : "回放本次骨架"; e.video.controls = replaying; e.video.pause(); if (replaying) { notice("Mode 3 回放只顯示本次模型骨架與初步資料品質診斷；不執行 Mode 2 classifier。"); replayFrame(); } else { draw({}); e.badge.textContent = "等待影片"; } });
e.downloadCsvBtn.addEventListener("click", () => { const headers = [...new Set(rows.flatMap(Object.keys))]; download("\ufeff" + [headers.join(","), ...rows.map(item => headers.map(key => escapeCsv(item[key])).join(","))].join("\n"), `${base()}_landmarks.csv`, "text/csv;charset=utf-8"); });
e.downloadMetadataBtn.addEventListener("click", () => download(JSON.stringify(metadata(), null, 2), `${base()}_metadata.json`, "application/json;charset=utf-8"));
