let mediaStream=null,recordStream=null,mediaRecorder=null,recordedChunks=[],recordingStartTime=null,timerInterval=null,prepInterval=null,recordingTimeout=null,isRecording=false,isPreparing=false,currentRecordingDuration=120000,lastRecordingLabel='120s',audioContext=null,currentRecorderMimeType='尚未錄影';
let pose=null,poseRunning=false,poseRafId=null,poseFrameCount=0,poseFpsLastTime=0,poseFps=0,latestPoseLandmarks=null,latestPoseStatus='尚未啟動';

const RECORDING_LENGTHS={'30':30000,'60':60000,'120':120000};
const PREP_COUNTDOWN_SECONDS=10;
const QUALITY_MODES={
 auto:{label:'自動模式',constraints:{}},
 '640x480_30':{label:'640 × 480 / 30fps',constraints:{width:{ideal:640},height:{ideal:480},frameRate:{ideal:30,max:30}}},
 '960x540_30':{label:'960 × 540 / 30fps',constraints:{width:{ideal:960},height:{ideal:540},frameRate:{ideal:30,max:30}}},
 '1280x720_30':{label:'1280 × 720 / 30fps',constraints:{width:{ideal:1280},height:{ideal:720},frameRate:{ideal:30,max:30}}}
};

const $=id=>document.getElementById(id);
const subjectCodeInput=$('subjectCode'),testPhaseSelect=$('testPhase'),cameraSelect=$('cameraSelect'),qualityModeSelect=$('qualityMode');
const refreshCamerasBtn=$('refreshCamerasBtn'),startCameraBtn=$('startCameraBtn'),stopCameraBtn=$('stopCameraBtn'),startRecordingBtn=$('startRecordingBtn'),stopRecordingBtn=$('stopRecordingBtn'),downloadBtn=$('downloadBtn');
const videoPreview=$('videoPreview'),outputCanvas=$('outputCanvas'),ctx=outputCanvas.getContext('2d');
const videoStatusOverlay=$('videoStatusOverlay'),videoTimerOverlay=$('videoTimerOverlay'),preCountdownOverlay=$('preCountdownOverlay'),timerDisplay=$('timerDisplay'),prepCountdownDisplay=$('prepCountdown');
const recordingLengthInputs=document.querySelectorAll('input[name="recordingLength"]'),timerSizeInputs=document.querySelectorAll('input[name="timerSize"]'),showSkeletonCheckbox=$('showSkeleton');
const cameraStatus=$('cameraStatus'),recordingStatus=$('recordingStatus'),downloadStatus=$('downloadStatus');
const diagCameraLabel=$('diagCameraLabel'),diagRequestedMode=$('diagRequestedMode'),diagResolution=$('diagResolution'),diagFrameRate=$('diagFrameRate'),diagAspectRatio=$('diagAspectRatio'),diagMimeType=$('diagMimeType'),diagPoseStatus=$('diagPoseStatus'),diagPoseFps=$('diagPoseFps'),diagRecordSource=$('diagRecordSource'),diagCapabilities=$('diagCapabilities'),diagRecommendation=$('diagRecommendation');

function showStatus(el,msg,type){el.textContent=msg;el.className=`status-message ${type}`;}
function formatTime(ms){const s=Math.ceil(ms/1000),m=Math.floor(s/60),r=s%60;return `${String(m).padStart(2,'0')}:${String(r).padStart(2,'0')}`;}
function generateFilename(code,phase,label){const n=new Date(),p=x=>String(x).padStart(2,'0');return `${code}_${phase}_${label}_skeleton_${n.getFullYear()}${p(n.getMonth()+1)}${p(n.getDate())}_${p(n.getHours())}${p(n.getMinutes())}.webm`;}
function getSelectedRecordingLength(){return Array.from(recordingLengthInputs).find(i=>i.checked)?.value||'120';}
function getSelectedRecordingLabel(){return `${getSelectedRecordingLength()}s`;}
function getSelectedRecordingDuration(){return RECORDING_LENGTHS[getSelectedRecordingLength()]||120000;}
function getSelectedTimerSize(){return Array.from(timerSizeInputs).find(i=>i.checked)?.value||'large';}
function applyTimerSize(){videoTimerOverlay.classList.remove('timer-normal','timer-large');videoTimerOverlay.classList.add(getSelectedTimerSize()==='normal'?'timer-normal':'timer-large');}
function getSelectedQualityModeKey(){return qualityModeSelect.value||'1280x720_30';}
function getSelectedQualityMode(){return QUALITY_MODES[getSelectedQualityModeKey()]||QUALITY_MODES['1280x720_30'];}
function safeRound(v,d=2){return typeof v==='number'?Number(v.toFixed(d)):'未提供';}
function formatRange(c){if(!c)return'未提供';if(Array.isArray(c))return c.join(', ');if(typeof c==='object')return `${c.min??'?'} – ${c.max??'?'}`;return String(c);}

function ensureAudioContext(){if(!audioContext){const A=window.AudioContext||window.webkitAudioContext;if(A)audioContext=new A();}if(audioContext&&audioContext.state==='suspended')audioContext.resume();}
function playTone(t,f,d){if(!audioContext)return;const o=audioContext.createOscillator(),g=audioContext.createGain();o.type='sine';o.frequency.setValueAtTime(f,t);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(.4,t+.02);g.gain.exponentialRampToValueAtTime(.0001,t+d);o.connect(g);g.connect(audioContext.destination);o.start(t);o.stop(t+d+.02);}
function playFinishBeep(){try{ensureAudioContext();if(!audioContext)return;const n=audioContext.currentTime;playTone(n,880,.18);playTone(n+.28,880,.18);playTone(n+.56,1046,.24);}catch(e){console.warn(e);}}

function setText(el,text){if(el)el.textContent=text;}
function resetDiagnostics(){setText(diagCameraLabel,'尚未啟動');setText(diagRequestedMode,getSelectedQualityMode().label);setText(diagResolution,'尚未啟動');setText(diagFrameRate,'尚未啟動');setText(diagAspectRatio,'尚未啟動');setText(diagMimeType,currentRecorderMimeType||'尚未錄影');setText(diagPoseStatus,'尚未啟動');setText(diagPoseFps,'尚未啟動');setText(diagRecordSource,'Canvas 骨架疊圖');setText(diagCapabilities,'啟動攝影機後顯示。');setText(diagRecommendation,'先用 640×480/30fps 測骨架穩定，再測 960×540/30fps 與 1280×720/30fps。');}
function summarizeCapabilities(c){if(!c)return'此瀏覽器或攝影機未提供 capabilities。';return [`width: ${formatRange(c.width)}`,`height: ${formatRange(c.height)}`,`frameRate: ${formatRange(c.frameRate)}`,`aspectRatio: ${formatRange(c.aspectRatio)}`,`facingMode: ${formatRange(c.facingMode)}`].join('\\n');}
function updateDiagnosticsFromTrack(track){if(!track){resetDiagnostics();return;}const s=track.getSettings?track.getSettings():{},c=track.getCapabilities?track.getCapabilities():null;diagCameraLabel.textContent=track.label||'未提供名稱';diagRequestedMode.textContent=getSelectedQualityMode().label;diagResolution.textContent=`${s.width||'未提供'} × ${s.height||'未提供'}`;diagFrameRate.textContent=s.frameRate!==undefined?`${safeRound(s.frameRate,2)} fps`:'未提供';if(diagAspectRatio)diagAspectRatio.textContent=s.aspectRatio!==undefined?safeRound(s.aspectRatio,3):(s.width&&s.height?safeRound(s.width/s.height,3):'未提供');diagMimeType.textContent=currentRecorderMimeType||'尚未錄影';diagCapabilities.textContent=summarizeCapabilities(c);diagRecommendation.textContent=s.frameRate&&s.frameRate<24?'目前實際幀率低於 24fps，建議改測 640×480/30fps 或自動模式。':'請觀察肩、肘、腕、髖骨架點是否穩定，尤其是手腕與手肘是否跳動。';}

async function refreshCameraList(){if(!navigator.mediaDevices?.enumerateDevices){showStatus(cameraStatus,'✗ 此瀏覽器不支援攝影機清單功能','error');return;}try{const devices=await navigator.mediaDevices.enumerateDevices(),videos=devices.filter(d=>d.kind==='videoinput'),cur=cameraSelect.value;cameraSelect.innerHTML='';const def=document.createElement('option');def.value='';def.textContent='預設攝影機（優先後鏡頭 / 外接鏡頭）';cameraSelect.appendChild(def);videos.forEach((d,i)=>{const o=document.createElement('option');o.value=d.deviceId;o.textContent=d.label||`攝影機 ${i+1}`;cameraSelect.appendChild(o);});if(cur&&Array.from(cameraSelect.options).some(o=>o.value===cur))cameraSelect.value=cur;showStatus(cameraStatus,videos.length?`✓ 已找到 ${videos.length} 個攝影機來源`:'尚未偵測到攝影機。請確認攝影機已連接。',videos.length?'success':'info');}catch(e){showStatus(cameraStatus,`✗ 取得攝影機清單失敗: ${e.message}`,'error');}}
function buildVideoConstraints(){const c={...getSelectedQualityMode().constraints};if(cameraSelect.value)c.deviceId={exact:cameraSelect.value};else c.facingMode={ideal:'environment'};return c;}

async function initPose(){if(pose)return pose;if(!window.Pose)throw new Error('MediaPipe Pose 尚未載入，請確認網路連線或 CDN 是否可用。');pose=new Pose({locateFile:file=>`https://cdn.jsdelivr.net/npm/@mediapipe/pose@0.5.1675469404/${file}`});pose.setOptions({modelComplexity:1,smoothLandmarks:true,enableSegmentation:false,smoothSegmentation:false,minDetectionConfidence:.5,minTrackingConfidence:.5});pose.onResults(onPoseResults);return pose;}

function resizeCanvasToVideo(){const w=videoPreview.videoWidth||1280,h=videoPreview.videoHeight||720;if(outputCanvas.width!==w||outputCanvas.height!==h){outputCanvas.width=w;outputCanvas.height=h;}}
function drawBaseFrame(){resizeCanvasToVideo();ctx.save();ctx.clearRect(0,0,outputCanvas.width,outputCanvas.height);ctx.drawImage(videoPreview,0,0,outputCanvas.width,outputCanvas.height);ctx.restore();}
function startPoseLoop(){if(poseRunning)return;poseRunning=true;poseFrameCount=0;poseFpsLastTime=performance.now();diagPoseStatus.textContent='骨架偵測啟動中';const loop=async()=>{if(!poseRunning||!mediaStream)return;if(videoPreview.readyState>=2){try{drawBaseFrame();await pose.send({image:videoPreview});poseFrameCount++;const now=performance.now();if(now-poseFpsLastTime>=1000){poseFps=poseFrameCount/((now-poseFpsLastTime)/1000);diagPoseFps.textContent=`${safeRound(poseFps,1)} fps`;poseFrameCount=0;poseFpsLastTime=now;}}catch(e){console.warn('MediaPipe 偵測錯誤:',e);diagPoseStatus.textContent='骨架偵測錯誤';}}poseRafId=requestAnimationFrame(loop);};loop();}
function stopPoseLoop(){poseRunning=false;if(poseRafId)cancelAnimationFrame(poseRafId);poseRafId=null;ctx.clearRect(0,0,outputCanvas.width,outputCanvas.height);diagPoseStatus.textContent='骨架偵測已停止';diagPoseFps.textContent='尚未啟動';}

function validLm(lm){return lm&&(lm.visibility===undefined||lm.visibility>=.35);}
function drawPoint(lm,color,label){const x=lm.x*outputCanvas.width,y=lm.y*outputCanvas.height;ctx.beginPath();ctx.arc(x,y,8,0,Math.PI*2);ctx.fillStyle=color;ctx.fill();ctx.lineWidth=3;ctx.strokeStyle='#fff';ctx.stroke();ctx.font='18px Arial';ctx.fillStyle='#fff';ctx.fillText(label,x+10,y-8);}
function drawLine(a,b,color){ctx.beginPath();ctx.moveTo(a.x*outputCanvas.width,a.y*outputCanvas.height);ctx.lineTo(b.x*outputCanvas.width,b.y*outputCanvas.height);ctx.lineWidth=6;ctx.strokeStyle=color;ctx.stroke();}
function drawSide(lms,side,color){const idx=side==='L'?{s:11,e:13,w:15,h:23}:{s:12,e:14,w:16,h:24},s=lms[idx.s],e=lms[idx.e],w=lms[idx.w],h=lms[idx.h];if(validLm(w)&&validLm(e))drawLine(w,e,color);if(validLm(e)&&validLm(s))drawLine(e,s,color);if(validLm(s)&&validLm(h))drawLine(s,h,color);if(validLm(s))drawPoint(s,color,`${side}肩`);if(validLm(e))drawPoint(e,color,`${side}肘`);if(validLm(w))drawPoint(w,color,`${side}腕`);if(validLm(h))drawPoint(h,color,`${side}髖`);}
function onPoseResults(results){drawBaseFrame();if(!showSkeletonCheckbox.checked){diagPoseStatus.textContent='骨架顯示關閉';return;}if(!results.poseLandmarks){diagPoseStatus.textContent='未偵測到人體';return;}diagPoseStatus.textContent='已偵測到人體骨架';drawSide(results.poseLandmarks,'L','#00e5ff');drawSide(results.poseLandmarks,'R','#ffeb3b');}

async function startCamera(){try{if(mediaStream)stopCamera();mediaStream=await navigator.mediaDevices.getUserMedia({video:buildVideoConstraints(),audio:false});videoPreview.srcObject=mediaStream;await videoPreview.play();await new Promise(r=>{if(videoPreview.videoWidth)r();else videoPreview.onloadedmetadata=r;});resizeCanvasToVideo();drawBaseFrame();startCameraBtn.disabled=true;stopCameraBtn.disabled=false;startRecordingBtn.disabled=false;cameraSelect.disabled=true;qualityModeSelect.disabled=true;updateStatusOverlay('待機');updateTimerOverlay(formatTime(getSelectedRecordingDuration()));updatePreCountdownOverlay('');applyTimerSize();updateDiagnosticsFromTrack(mediaStream.getVideoTracks()[0]);showStatus(cameraStatus,'✓ 攝影機已啟動，MediaPipe 骨架偵測準備中','success');await initPose();startPoseLoop();await refreshCameraList();cameraSelect.disabled=true;}catch(e){console.error(e);showStatus(cameraStatus,`✗ 錯誤: ${e.message}`,'error');}}
function stopCamera(){stopPoseLoop();if(mediaStream)mediaStream.getTracks().forEach(t=>t.stop());mediaStream=null;videoPreview.srcObject=null;if(isRecording||isPreparing)stopRecording();startCameraBtn.disabled=false;stopCameraBtn.disabled=true;startRecordingBtn.disabled=true;stopRecordingBtn.disabled=true;cameraSelect.disabled=false;qualityModeSelect.disabled=false;updateStatusOverlay('攝影機未啟動');updateTimerOverlay('00:00');updatePreCountdownOverlay('');resetDiagnostics();showStatus(cameraStatus,'✓ 攝影機已停止','info');}

function startRecording(){if(isPreparing||isRecording)return;if(!subjectCodeInput.value.trim()){showStatus(recordingStatus,'✗ 請輸入受試者代碼','error');return;}if(!testPhaseSelect.value){showStatus(recordingStatus,'✗ 請選擇測驗階段','error');return;}if(!mediaStream){showStatus(recordingStatus,'✗ 攝影機尚未啟動','error');return;}ensureAudioContext();applyTimerSize();currentRecordingDuration=getSelectedRecordingDuration();lastRecordingLabel=getSelectedRecordingLabel();subjectCodeInput.disabled=true;testPhaseSelect.disabled=true;recordingLengthInputs.forEach(i=>i.disabled=true);timerSizeInputs.forEach(i=>i.disabled=true);stopCameraBtn.disabled=true;startRecordingBtn.disabled=true;stopRecordingBtn.disabled=true;downloadBtn.disabled=true;let prepSeconds=PREP_COUNTDOWN_SECONDS;updateStatusOverlay('預備中');updateTimerOverlay(formatTime(currentRecordingDuration));updatePreCountdownOverlay(String(prepSeconds));isPreparing=true;prepCountdownDisplay.textContent=String(prepSeconds);showStatus(recordingStatus,'● 預備倒數中...','info');showStatus(downloadStatus,'','info');prepInterval=setInterval(()=>{prepSeconds-=1;if(prepSeconds>0){prepCountdownDisplay.textContent=String(prepSeconds);updatePreCountdownOverlay(String(prepSeconds));return;}clearInterval(prepInterval);prepInterval=null;prepCountdownDisplay.textContent='開始';updatePreCountdownOverlay('開始');setTimeout(()=>beginRecording(),350);},1000);}
function beginRecording(){recordedChunks=[];const fps=Math.round(mediaStream.getVideoTracks()[0].getSettings().frameRate||30);recordStream=outputCanvas.captureStream(Math.max(15,Math.min(30,fps)));let options={mimeType:'video/webm;codecs=vp9'};if(!MediaRecorder.isTypeSupported(options.mimeType))options.mimeType='video/webm;codecs=vp8';if(!MediaRecorder.isTypeSupported(options.mimeType))options.mimeType='video/webm';try{mediaRecorder=new MediaRecorder(recordStream,options);}catch(e){mediaRecorder=new MediaRecorder(recordStream);}currentRecorderMimeType=mediaRecorder.mimeType||options.mimeType||'瀏覽器預設';diagMimeType.textContent=currentRecorderMimeType;mediaRecorder.ondataavailable=e=>{if(e.data.size>0)recordedChunks.push(e.data);};mediaRecorder.onstop=()=>{window.recordedBlob=new Blob(recordedChunks,{type:mediaRecorder.mimeType||'video/webm'});downloadBtn.disabled=false;updateStatusOverlay('✓ 錄製完成');updateTimerOverlay('00:00');updatePreCountdownOverlay('');showStatus(recordingStatus,'✓ 骨架疊圖影片錄製已完成','success');showStatus(downloadStatus,'✓ 可以下載骨架疊圖影片','success');playFinishBeep();};mediaRecorder.start();recordingStartTime=Date.now();isRecording=true;isPreparing=false;stopRecordingBtn.disabled=false;timerDisplay.classList.add('recording');updateStatusOverlay('● 錄製中');updateTimerOverlay(formatTime(currentRecordingDuration));updatePreCountdownOverlay('');prepCountdownDisplay.textContent='';showStatus(recordingStatus,'● 錄製骨架疊圖影片中...','info');updateTimer();timerInterval=setInterval(updateTimer,100);recordingTimeout=setTimeout(()=>{if(isRecording)stopRecording();},currentRecordingDuration);}
function stopRecording(){if(!isRecording&&!isPreparing)return;if(prepInterval)clearInterval(prepInterval);if(recordingTimeout)clearTimeout(recordingTimeout);if(timerInterval)clearInterval(timerInterval);prepInterval=null;recordingTimeout=null;timerInterval=null;const wasRecording=isRecording;isRecording=false;isPreparing=false;recordingStartTime=null;timerDisplay.textContent='00:00';timerDisplay.classList.remove('recording');prepCountdownDisplay.textContent='';updatePreCountdownOverlay('');if(wasRecording&&mediaRecorder&&mediaRecorder.state!=='inactive')mediaRecorder.stop();else{updateStatusOverlay('待機');updateTimerOverlay(formatTime(getSelectedRecordingDuration()));}startRecordingBtn.disabled=!mediaStream;stopRecordingBtn.disabled=true;subjectCodeInput.disabled=false;testPhaseSelect.disabled=false;recordingLengthInputs.forEach(i=>i.disabled=false);timerSizeInputs.forEach(i=>i.disabled=false);stopCameraBtn.disabled=false;showStatus(recordingStatus,wasRecording?'✓ 錄製已停止':'準備就緒',wasRecording?'success':'info');}
function updateTimer(){if(!recordingStartTime||!isRecording)return;const remain=Math.max(0,currentRecordingDuration-(Date.now()-recordingStartTime));timerDisplay.textContent=formatTime(remain);updateTimerOverlay(formatTime(remain));}
function updateStatusOverlay(text){videoStatusOverlay.textContent=text;videoStatusOverlay.classList.remove('status-idle','status-preparing','status-recording','status-complete','status-camera-off');if(text==='待機')videoStatusOverlay.classList.add('status-idle');else if(text==='預備中')videoStatusOverlay.classList.add('status-preparing');else if(text.includes('錄製中'))videoStatusOverlay.classList.add('status-recording');else if(text.includes('錄製完成'))videoStatusOverlay.classList.add('status-complete');else if(text==='攝影機未啟動')videoStatusOverlay.classList.add('status-camera-off');}
function updateTimerOverlay(text){videoTimerOverlay.textContent=text;}
function updatePreCountdownOverlay(text){if(text&&String(text).trim()!==''){preCountdownOverlay.textContent=text;preCountdownOverlay.classList.remove('hidden');}else{preCountdownOverlay.textContent='';preCountdownOverlay.classList.add('hidden');}}
function downloadVideo(){if(!window.recordedBlob){showStatus(downloadStatus,'✗ 沒有可下載的影片','error');return;}const filename=generateFilename(subjectCodeInput.value.trim(),testPhaseSelect.value,lastRecordingLabel);const url=URL.createObjectURL(window.recordedBlob),link=document.createElement('a');link.href=url;link.download=filename;document.body.appendChild(link);link.click();document.body.removeChild(link);URL.revokeObjectURL(url);showStatus(downloadStatus,`✓ 正在下載: ${filename}`,'success');}

refreshCamerasBtn.addEventListener('click',refreshCameraList);startCameraBtn.addEventListener('click',startCamera);stopCameraBtn.addEventListener('click',stopCamera);startRecordingBtn.addEventListener('click',startRecording);stopRecordingBtn.addEventListener('click',stopRecording);downloadBtn.addEventListener('click',downloadVideo);
recordingLengthInputs.forEach(i=>i.addEventListener('change',()=>{if(!isRecording&&!isPreparing){const d=getSelectedRecordingDuration();updateTimerOverlay(formatTime(d));timerDisplay.textContent=formatTime(d);}}));
timerSizeInputs.forEach(i=>i.addEventListener('change',()=>{if(!isRecording&&!isPreparing)applyTimerSize();}));
qualityModeSelect.addEventListener('change',()=>{if(!isRecording&&!isPreparing){diagRequestedMode.textContent=getSelectedQualityMode().label;if(mediaStream)showStatus(cameraStatus,'畫質模式已變更，請停止攝影機後重新啟動才會套用。','info');}});
showSkeletonCheckbox.addEventListener('change',()=>{diagPoseStatus.textContent=showSkeletonCheckbox.checked?'骨架顯示開啟':'骨架顯示關閉';});
if(navigator.mediaDevices?.addEventListener)navigator.mediaDevices.addEventListener('devicechange',refreshCameraList);
document.addEventListener('DOMContentLoaded',()=>{timerDisplay.textContent=formatTime(getSelectedRecordingDuration());prepCountdownDisplay.textContent='準備就緒';updateStatusOverlay('待機');updateTimerOverlay(formatTime(getSelectedRecordingDuration()));updatePreCountdownOverlay('');applyTimerSize();resetDiagnostics();showStatus(cameraStatus,'請啟動攝影機。V2.0.2 會將攝影機畫面與骨架一起畫到 Canvas，並錄製 Canvas。','info');showStatus(recordingStatus,'準備就緒','info');showStatus(downloadStatus,'','info');refreshCameraList();});
console.log('CPR 研究用網頁系統 V2.0.2 已載入');
